### PR TITLE
Remove references to LESS CSS preprocessor

### PR DESCRIPTION
**Pull request by specious**
This fixes an issue with some styles not being applied properly, and the location map not showing up in certain web browsers.

### CODE REVIEW

**Comment by victor-rocha** [comment]
I think the plan was to use less instead we end up using css and our less setup became pointless.

👍

**Comment by adamajm** [comment]
seems like the UI is all screwy now...

**Comment by victor-rocha** [comment]
What do you mean, adam? It looks fine to me

On Tue, May 17, 2016 at 9:05 AM, adamajm <notifications@github.com> wrote:

> seems like the UI is all screwy now...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/codefordurham/Durham-Restaurants/pull/149#issuecomment-219711286>
>



-- 
Thanks,
Victor

**Comment by specious** [comment]
@adamajm, could you describe the behavior(s) you are experiencing versus the functionality you expect?  Opening issues for each individual aspect could help developers start implementing relevant changes.

**Pull request merged**
